services:
  go1:
    build: ./go1
    container_name: go1
    ports:
      - "5001:8080"

  go2:
    build: ./go2
    container_name: go2
    ports:
      - "5002:8080"

  go3:
    build: ./go3
    container_name: go3
    ports:
      - "5003:8080"
  
  nginx:
    build: ./nginx
    ports:
      - "5004:80"
    environment:
      - NGINX_PORT=80
      